### ISSUE TITLE
Dim the RGB led on the config option page of the web server. Or even better have a level setup for dimming and for off.

### ISSUE THREAD

**Issue by robouden** [Safecast/bGeigieNanokit-Xbee#16]

**Comment by Claypuppet** [comment]
@robouden Nice way to discuss other features like this. Lets try to put all our tasks in as issues so we can discuss (and keep track of) progress as well.

**Comment by robouden** [comment]
Agreed :)

**Comment by robouden** [comment]
Yes, what issues do you have open?
