### ISSUE TITLE
Check if bluetooth is stable during sleep

### ISSUE THREAD

**Issue by Claypuppet** [Safecast/bGeigieNanokit-Xbee#30]
Check if the bluetooth pairing drops with the sleep

Bluetooth data is send every 5 seconds, before sending, bluetooth is initialized again. If the bluetooth is unstable there will need to be an option to enable bluetooth in the config.

**Comment by Claypuppet** [comment]
Looks like bluetooth does not work in between sleeps, so its useless for mobile mode (where the sleep was mostly needed). 

Need to discuss how we continue on this.

**Comment by robouden** [comment]
Maybe put the issue with a  "to be research label"
