### ISSUE TITLE
Auto switch from mobile to fixed mode (if enabled)

### ISSUE THREAD

**Issue by Claypuppet** [Safecast/bGeigieNanokit-Xbee#33]
Check in mobile mode if: 
* auto switch is enabled
* current location is near home location
* current location has been near home location for some time (5 min~)

Then check for wifi availability (thanks Rob) -> switch to fixed mode

--
Update this in state machine, new transition from mobile -> fixed

**Comment by robouden** [comment]
Home location and also be autodetecting the wifi SSID and local GPS.

**Comment by Claypuppet** [comment]
Right! Will add that as well
