### ISSUE TITLE
Find a way to make configuring "my home location" easier for the user

### ISSUE THREAD

**Issue by Claypuppet** [Safecast/bGeigieNanokit-Xbee#35]
maybe some button "use current location" or get the location of the first reading...

**Comment by robouden** [comment]
Or get the location from the first 1 minute. Or manually enter the LAT and LON for the location.

**Comment by Claypuppet** [comment]
Manually enter would be step one (in the config issue #32 )

**Comment by Claypuppet** [comment]
Implemented this by saving the last know gps location (updating every time a new reading is parsed).

on config page the location is displayed with a "use this location" button to set the home location.
