### ISSUE TITLE
Create a board for ESP32 Xbee

### ISSUE THREAD

**Issue by robouden** [Safecast/bGeigieNanokit-Xbee#40]
-2019-07-7 V1.4.0 (QR code changed and resistor removed shipped to KW)
-2019-05-09 send V1.2.0 to dirtypcbs.com
- 2019-04-30
     V1.2.0 of the board with no copyright, and 330uF cap. Needs also 1-ohm resistor in VCC line to the prevent reset of FIO.
- 2019-03-26 update
     first boards are made
-2019-04-03
     send final boards to Dirty PCB

**Comment by Claypuppet** [comment]
Pieter also mentioned that the contact address should be info@safecast

**Comment by robouden** [comment]
Yes, better.
