### ISSUE TITLE
finish manual

### ISSUE THREAD

**Issue by robouden** [Safecast/bGeigieNanokit-Xbee#54]
Some parts are not finished.

**Comment by robouden** [comment]
I will add my notes a bit later.. In the wrong format now.

https://docs.google.com/document/d/1yKs4lCmWOe3gOA4Q1oEda-JCmuCUdLt6Pk29f4h0Nmw/edit

**Comment by Claypuppet** [comment]
So as for your notes:
- Prepare for long time sensor: I wanted to link to different page here with dock & wireless charging instructions: how to print the dock, but more importantly, how to connect the wireless receiver. Lets discuss this first before we make the guide.
- Troubleshooting: Yes still need to think of ways to troubleshoot
- Dev environment: For Arduino IDE i will do the steps myself on my desktop (clean environment) and write those down, maybe you can write something for VSCodium?
- Designs: That image is "outdated" as the sequence is now in the state machine. I could create a simpler diagram with loop just for the whole data flow
- Design choices, not sure what to do with this one, quite outdated..
- Things needed for fixed sensor: I think this will fit well in the user manual (required software / hardware), we can link from other pages to there

Can we make some separate issues for these?

**Comment by robouden** [comment]
Yes, a good idea to make separate issues out of them.
