### ISSUE TITLE
Device Settings wont get saved

### ISSUE THREAD

**Issue by BRSMaulwurf** [Safecast/bGeigieNanokit-Xbee#60]
Im currently running firmware V1.5
and the device setting "Wifi Server" wont get saved after power lost.
All the other settings like Wifi-Password, API-Key, etc. remains after shut down the bGeigie.

![grafik](https://github.com/user-attachments/assets/8b331316-b34a-480f-a052-72f72e9781dc)

**Comment by robouden** [comment]
BRS,

You want the page to be able enabled/accessible over your wifi network?

Regards
Rob

**Comment by BRSMaulwurf** [comment]
Yes. I want to put my bGeigie in a hard case on my balcony as stationary sensor. Therefore it would be nice to be able to access the cast plattform via wifi for firmware updates and settings. I dont want to demount the case, and open it, to activate the configuration mode manually. 
If the wifi network platform is enabled the whole time even after a power lost, this would be perfect.  The plattform works perfectly, but i have to enable it every time after i shut the system off, and this is anoying.

Maybe later it would be possible to show the latest CPM readings or other statistics on this web platform too 😲

Best regards
Philipp

**Comment by robouden** [comment]
Phillip,

Thanks for the explanation. 
I hope Jelle can make a fix for the stickiness of status of the Wi-Fi server settings for it soon.

Regards
Rob  Oudendijk

**Comment by BRSMaulwurf** [comment]
I´ve seen there is an update on this request. 
Is the "firmeware-1.5.bin" in [bGeigieCast/firmware/](https://github.com/Safecast/bGeigieCast/tree/updates-july-2023_M5stampS3_1-6-2_boards/firmware) the new update? 
Shouldn´t this be version 1.6? because 1.5 is already existing in the other folders.

Best regards and thanks for the update
Philipp

**Comment by robouden** [comment]
Philip,

V1.5 is the latest with the fix mentioned.

Hugs and peace,
rob
