### ISSUE TITLE
bGeigieCast adapter kicad/gerber files for stamp-S3 version1.6.2 is missing

### ISSUE THREAD

**Issue by 3uky** [Safecast/bGeigieNanokit-Xbee#61]
Latest uploaded version for cast adapter is 1.6.1 but newer version [1.6.2](https://raw.githubusercontent.com/Safecast/bGeigieCast/development/images/wiki/S4900033.jpg) is missing from git repository. I believe this is latest version. Could you please upload those files.

**Comment by robouden** [comment]
3uky,

Just updated the files. The files were not so good organized. Maybe cleaner now. V1.6.2 seems correct now.
I will also export the Gerber file (in case you do not run the nightly build of KiCad and can not open the files). 

Regards
Rob Oudendijk

**Comment by 3uky** [comment]
Thank you Rob. I have access to nightly builds so working with kicad files is no issue. I looked on changes in updates-july-2023_M5stampS3_1-6-2_boards branch and I believe that merge with development branch result in corruption of several gerber/kicad files so it would be better to reset branch and merge it again. I reset branch on my local to point before merge and get to the files what I needed.

**Comment by robouden** [comment]
Hynek,


Thanks for mention it.
I resented the branch and merge it into development branch.

Regards
Rob Oudendijk
